name: "💡 Feature Request"
description: Create a new ticket for a new feature request
title: "ItemProperty: <title>"
labels: ["ultima-online", "triage", "item-property"]

body:
  - type: input
    id: name
    attributes:
      label: Name
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe the mechanic of item property.
    validations:
      required: true

  - type: textarea
    id: mechanic-pvm
    attributes:
      label: Game Mechanic (PVM)
      description: |
        Specify the mechanic for player versus monsters.
    validations:
      required: true

  - type: textarea
    id: mechanic-pvp
    attributes:
      label: Game Mechanic (PVP)
      description: |
        Specify the additional mechanic for player versus player.

  - type: input
    id: intensity-range
    attributes:
      label: Intensity Range
      description: |
        Possible Intensity Range fixed, values or %
    validations:
      required: true

  - type: input
    id: imbue-weight
    attributes:
      label: Imbue Weight

  - type: input
    id: total-cap
    attributes:
      label: Total Cap
    validations:
      required: true

  - type: checkboxes
    id: found-on
    attributes:
      label: Found on
      options:
        - Armor
        - Jewelry
        - Shields
        - Spellbooks
        - Weapons
        - Unknown
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Found on
      multiple: true
      options:
        - Persistent
        - Hit
        - Permament
        - Unknown
    validations:
      required: true

  - type: dropdown
    id: era
    attributes:
      label: Initial Era
      options:
        - Classic (Pre-T2A)
        - The Second Age (T2A)
        - Renaissance (UOR)
        - Third Dawn (TD)
        - Lord Blackthorns Revenge (LBR)
        - Age of Shadows (AOS)
        - Samurai Empire (SE)
        - Mondains Legacy (ML)        
        - Kingdom Reborn (KR)
        - Stygian Abyss (SA)
        - High Seas (HS)
        - Time of Legends (TOL)
        - New Legacy (NL)
        - Unknown
    validations:
      required: true
      
  - type: input
    id: publish
    attributes:
      label: Initial Publish
      description: Whats the initial publish?
      placeholder: unknown
    validations:
      required: false