del /f .\Projects\*\obj

del /f .\Distribution\Assemblies\BouncyCastle.Crypto.dll
del /f .\Distribution\Assemblies\MailKit.dll
del /f .\Distribution\Assemblies\Microsoft.AspNetCore.Connections.Abstractions.dll
del /f .\Distribution\Assemblies\Microsoft.AspNetCore.Http.Features.dll
del /f .\Distribution\Assemblies\Microsoft.Extensions.Configuration.Abstractions.dll
del /f .\Distribution\Assemblies\Microsoft.Extensions.DependencyInjection.Abstractions.dll
del /f .\Distribution\Assemblies\Microsoft.Extensions.FileProviders.Abstractions.dll
del /f .\Distribution\Assemblies\Microsoft.Extensions.Hosting.Abstractions.dll
del /f .\Distribution\Assemblies\Microsoft.Extensions.Logging.Abstractions.dll
del /f .\Distribution\Assemblies\Microsoft.Extensions.Primitives.dll
del /f .\Distribution\Assemblies\MimeKit.dll
del /f .\Distribution\Assemblies\System.IO.Pipelines.dll

del /f .\Distribution\libdrng.dll
del /f .\Distribution\libuv.dll
del /f .\Distribution\libuv.so
del /f .\Distribution\Microsoft.AspNetCore.Connections.Abstractions.dll
del /f .\Distribution\Microsoft.AspNetCore.Http.Features.dll
del /f .\Distribution\Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.dll
del /f .\Distribution\Microsoft.Extensions.Configuration.Abstractions.dll
del /f .\Distribution\Microsoft.Extensions.DependencyInjection.Abstractions.dll
del /f .\Distribution\Microsoft.Extensions.FileProviders.Abstractions.dll
del /f .\Distribution\Microsoft.Extensions.Hosting.Abstractions.dll
del /f .\Distribution\Microsoft.Extensions.Logging.Abstractions.dll
del /f .\Distribution\Microsoft.Extensions.Options.dll
del /f .\Distribution\Microsoft.Extensions.Primitives.dll
del /f .\Distribution\ModernUO
del /f .\Distribution\ModernUO.deps.json
del /f .\Distribution\ModernUO.dll
del /f .\Distribution\ModernUO.dll.config
del /f .\Distribution\ModernUO.exe
del /f .\Distribution\ModernUO.pdb
del /f .\Distribution\ModernUO.runtimeconfig.dev.json
del /f .\Distribution\ModernUO.runtimeconfig.json
del /f .\Distribution\System.IO.Pipelines.dll
del /f .\Distribution\zlib.dll
