rm -rf Projects/*/obj
rm -rf Projects/*/bin

rm -f Distribution/Assemblies/BouncyCastle.Crypto.dll
rm -f Distribution/Assemblies/MailKit.dll
rm -f Distribution/Assemblies/Microsoft.AspNetCore.Connections.Abstractions.dll
rm -f Distribution/Assemblies/Microsoft.AspNetCore.Http.Features.dll
rm -f Distribution/Assemblies/Microsoft.Extensions.Configuration.Abstractions.dll
rm -f Distribution/Assemblies/Microsoft.Extensions.DependencyInjection.Abstractions.dll
rm -f Distribution/Assemblies/Microsoft.Extensions.FileProviders.Abstractions.dll
rm -f Distribution/Assemblies/Microsoft.Extensions.Hosting.Abstractions.dll
rm -f Distribution/Assemblies/Microsoft.Extensions.Logging.Abstractions.dll
rm -f Distribution/Assemblies/Microsoft.Extensions.Primitives.dll
rm -f Distribution/Assemblies/MimeKit.dll
rm -f Distribution/Assemblies/System.IO.Pipelines.dll
rm -f Distribution/Assemblies/Argon2.Bindings.dll
rm -f Distribution/Assemblies/libargon2.so
rm -f Distribution/Assemblies/libargon2.dylib
rm -f Distribution/Assemblies/argon2.dll

rm -f Distribution/libdrng.dll
rm -f Distribution/libuv.dll
rm -f Distribution/libuv.so
rm -f Distribution/libuv.dylib
rm -f Distribution/Microsoft.AspNetCore.Connections.Abstractions.dll
rm -f Distribution/Microsoft.AspNetCore.Http.Features.dll
rm -f Distribution/Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.dll
rm -f Distribution/Microsoft.Extensions.Configuration.Abstractions.dll
rm -f Distribution/Microsoft.Extensions.DependencyInjection.Abstractions.dll
rm -f Distribution/Microsoft.Extensions.FileProviders.Abstractions.dll
rm -f Distribution/Microsoft.Extensions.Hosting.Abstractions.dll
rm -f Distribution/Microsoft.Extensions.Logging.Abstractions.dll
rm -f Distribution/Microsoft.Extensions.Options.dll
rm -f Distribution/Microsoft.Extensions.Primitives.dll
rm -f Distribution/ModernUO
rm -f Distribution/ModernUO.deps.json
rm -f Distribution/ModernUO.dll
rm -f Distribution/ModernUO.dll.config
rm -f Distribution/ModernUO.exe
rm -f Distribution/ModernUO.pdb
rm -f Distribution/ModernUO.runtimeconfig.dev.json
rm -f Distribution/ModernUO.runtimeconfig.json
rm -f Distribution/System.IO.Pipelines.dll
rm -f Distribution/zlib.dll
